version: '3.8'
services:
    nginx:
        build:
            context: ./frontend
        ports:
            - 5173:80
        depends_on:
            - spring

    spring:
        build:
            context: ./backend
        ports:
            - 8082:8081 #로컬포트:컨테이너포트
